//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studentqu
{
    using System;
    using System.Collections.Generic;
    
    public partial class questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public questions()
        {
            this.test_reports = new HashSet<test_reports>();
        }
    
        public int question_id { get; set; }
        public string question_type { get; set; }
        public string question_text { get; set; }
        public string answer_option_1 { get; set; }
        public string answer_option_2 { get; set; }
        public string answer_option_3 { get; set; }
        public string answer_option_4 { get; set; }
        public Nullable<int> correct_answer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_reports> test_reports { get; set; }
    }
}
